name: sync-fork
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Merge upstream changes
        run: |
          git config --global user.name 'continuous-integration'
          git config --global user.email 'username@users.noreply.github.com'

          git remote add upstream git@github.com:simolus3/sqlite3.dart.git
          git fetch upstream

          git checkout -b chore/update-sqlite3-upstream
          git merge --no-edit upstream/main
          git push origin chore/update-sqlite3-upstream

          gh pr create --title "chore: update sqlite3 upstream" --body "This PR updates the upstream branch to the latest changes from the original repository." --base main --head chore/update-sqlite3-upstream
