name: sync-fork
on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: "0"
          token: ${{ secrets.PAT_TOKEN }}
      - name: Check if branch exists
        id: check-branch
        run: |
          branch_name="chore/update-sqlite3-upstream"
          if [ `git branch --list $branch_name` ]
          then
            echo "Branch already exists"
            exit 1
          fi
      - name: Set config
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/simolus3/sqlite3.dart.git
          git fetch upstream
      - name: Merge upstream changes
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          git checkout -b chore/update-sqlite3-upstream main
          git push --set-upstream origin chore/update-sqlite3-upstream
          lines=$( git diff main..upstream/main -- . ':(exclude).github/**' | wc -l )
          echo "Number of detected line changes: $lines"
          if [ $lines -gt 0 ]; then
            git merge upstream/main
            git merge --no-edit upstream/main
            git push origin chore/update-sqlite3-upstream
            gh pr create --title "chore: update sqlite3 upstream" --body "This PR updates the upstream branch to the latest changes from the original repository." --base main --head chore/update-sqlite3-upstream
          fi
